# Generated by Django 4.1.2 on 2022-11-09 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id_comic', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('reading', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('want_to_read', models.BooleanField()),
                ('cover', models.ImageField(default='', upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
