# Generated by Django 4.1.2 on 2022-11-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
