# Generated by Django 4.1.2 on 2022-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_alter_comics_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
